[package]
name = "lhm-service"
version = "0.0.0"
edition = "2024"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/jacobtread/lhm"
readme = "README.md"
description = "Wrapper around Libre Hardware Monitor to request hardware (and temperatures)"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.38", features = ["derive"] }
dlopen = "0.1"
dlopen_derive = "0.1.4"
interprocess = "2.2.3"
num_enum = "0.7.3"
recvmsg = "1.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tracing = { version = "0.1.41", features = ["log"] }
widestring = "1.2.0"
windows-service = "0.7"
windows-sys = { version = "0.52", features = ["Win32_Security"] }
