[package]
name = "lhm-client"
version = "0.1.0"
edition = "2024"

[dependencies]
interprocess = { version = "2.2.3", features = ["tokio"] }
tokio = { version = "1.45.0", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

lhm-shared = { version = "*", path = "../lhm-shared" }
