[package]
name = "lhm-client"
version = "0.0.0"
edition = "2024"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/jacobtread/lhm-service"
readme = "README.md"
description = "Client for using the LHM service"

[dependencies]
interprocess = { workspace = true }
serde_json = { workspace = true }

tokio = { version = "1", features = [] }

# Shared structures
lhm-shared = { version = "0.0.0", path = "../lhm-shared" }

[dev-dependencies]
tokio = { version = "1", features = ["macros"] }
